#include "PageGeometry.h"

PageGeometry::PageGeometry(QWizard *parent): QWizardPage(parent)
{
    QLabel *statictext_TODO = new QLabel("Configuration of geometry (placing primitives, stl import, hyperlynx import) TO BE DONE", this);
    statictext_TODO->setGeometry(QRect(QPoint(22, 20), QSize(500, 30)));

}


bool PageGeometry::validatePage()
{
    SaveToSimScriptBuffer();
    return true;
}


void PageGeometry::SaveToSimScriptBuffer(void)
{
    text_save_to_simscript.clear();
    text_save_to_simscript.append("##<OUTPUT_AUTOGENERATED_PageGeometry>##\n");


    text_save_to_simscript.append("##<END_OUTPUT_AUTOGENERATED_PageGeometry>##\n");
    qDebug("%s", qUtf8Printable(text_save_to_simscript));
}


void PageGeometry::ReadFromSimScriptBuffer(void)
{

}
