#include "PageGeometry.h"

PageGeometry::PageGeometry(QWizard *parent, VariablesEditor *var_edit_main): QWizardPage(parent)
{
    QVector<shape_parameters *> *shapes_param_list = new QVector<shape_parameters *>;
    shapes_param_list_ptr = shapes_param_list;
    var_edit = var_edit_main;

    ShapeSelectLayout();
    ShapeListLayout();
    ShapeTransformsLayout();

    ShapeBoxSettings();
    ShapeCylinderSettings();

    stackedLayout = new QStackedLayout;
    stackedLayout->addWidget(groupbox_box_settings);
    stackedLayout->addWidget(groupbox_cylinder_settings);



    main_layout_shapes = new QHBoxLayout;
    main_layout_shapes->addWidget(shape_select_groupbox);
    main_layout_shapes->addLayout(stackedLayout);
    main_layout_shapes->addWidget(shape_list_groupbox);
    main_layout_shapes->addWidget(transforms_groupbox);

    setLayout(main_layout_shapes);
}


bool PageGeometry::validatePage()
{
    SaveToSimScriptBuffer();
    return true;
}


void PageGeometry::SaveToSimScriptBuffer(void)
{
    text_save_to_simscript.clear();
    text_save_to_simscript.append("##<OUTPUT_AUTOGENERATED_PageGeometry>##\n");

    for(int i_sh = 0; i_sh < shapes_param_list_ptr->count(); ++i_sh)
    {
        if(shapes_param_list_ptr->at(i_sh)->type == "box")
        {
            shape_box_parameters *shape_box_tmp = (shape_box_parameters *)(shapes_param_list_ptr->at(i_sh));
            text_save_to_simscript.append(QString("CSX = AddBox(CSX, '%1', %2, ").arg(shape_box_tmp->material).arg(shape_box_tmp->priority));
            text_save_to_simscript.append(QString("[%1 %2 %3] ").arg(EvaluateVar(shape_box_tmp->x_coord_1)).arg(shape_box_tmp->y_coord_1).arg(shape_box_tmp->z_coord_1));
            text_save_to_simscript.append(QString("[%1 %2 %3]").arg(shape_box_tmp->x_coord_2).arg(shape_box_tmp->y_coord_2).arg(shape_box_tmp->z_coord_2));

            if(shape_box_tmp->transf_order[0] == "Scale" || shape_box_tmp->transf_order[0] == "Rotate" || shape_box_tmp->transf_order[0] == "Move")
            {
                text_save_to_simscript.append(QString(", 'Transform',{"));
                for(int i_tr = 0; shape_box_tmp->transf_order[i_tr] != "" && i_tr < 3; ++i_tr)
                {
                    if(shape_box_tmp->transf_order[i_tr] == "Scale")
                        text_save_to_simscript.append(QString("'Scale', '%1,%2,%3', ").arg(shape_box_tmp->transf_scale_x).arg(shape_box_tmp->transf_scale_y).arg(shape_box_tmp->transf_scale_z));
                    if(shape_box_tmp->transf_order[i_tr] == "Rotate")
                        text_save_to_simscript.append(QString("'Rotate', '%1, %2, %3, %4', ").arg(shape_box_tmp->transf_rotate_ax).arg(shape_box_tmp->transf_rotate_ay).arg(shape_box_tmp->transf_rotate_az).arg(shape_box_tmp->transf_rotate_angle));
                    if(shape_box_tmp->transf_order[i_tr] == "Move")
                        text_save_to_simscript.append(QString("'Translate', '%1,%2,%3', ").arg(shape_box_tmp->transf_move_x).arg(shape_box_tmp->transf_move_y).arg(shape_box_tmp->transf_move_z));
                }
                text_save_to_simscript.chop(2); //cut the last space and comma
                text_save_to_simscript.append(QString("}"));
            }
            text_save_to_simscript.append(QString(");\n"));
        }
        else if(shapes_param_list_ptr->at(i_sh)->type == "cylinder")
        {
            shape_cylinder_parameters *shape_cylinder_tmp = (shape_cylinder_parameters *)(shapes_param_list_ptr->at(i_sh));
            text_save_to_simscript.append(QString("CSX = AddCylinder(CSX, '%1', %2, ").arg(shape_cylinder_tmp->material).arg(shape_cylinder_tmp->priority));
            text_save_to_simscript.append(QString("[%1 %2 %3], ").arg(shape_cylinder_tmp->x_coord_1).arg(shape_cylinder_tmp->y_coord_1).arg(shape_cylinder_tmp->z_coord_1));
            text_save_to_simscript.append(QString("[%1 %2 %3], ").arg(shape_cylinder_tmp->x_coord_2).arg(shape_cylinder_tmp->y_coord_2).arg(shape_cylinder_tmp->z_coord_2));
            text_save_to_simscript.append(QString("%1);\n").arg(shape_cylinder_tmp->radius));
        }
    }

    text_save_to_simscript.append("##<END_OUTPUT_AUTOGENERATED_PageGeometry>##\n");
    qDebug("%s", qUtf8Printable(text_save_to_simscript));
}


void PageGeometry::ReadFromSimScriptBuffer(void)
{

}


void PageGeometry::UploadShapesToViewer(void)
{

}


void PageGeometry::ShapeSelectLayout(void)
{
    shape_select_groupbox = new QGroupBox(tr("Select shape type"));
    QGridLayout *grid_layout_select_shape = new QGridLayout;

    rad_but_type_box = new QRadioButton("Box", this);
    rad_but_type_sphere = new QRadioButton("Sphere", this);
    rad_but_type_spherical_shell = new QRadioButton("Spherical Shell", this);
    rad_but_type_cylinder = new QRadioButton("Cylinder", this);
    rad_but_type_cylindrical_shell = new QRadioButton("Cylindrical Shell", this);
    rad_but_type_curve = new QRadioButton("Curve", this);
    rad_but_type_wire = new QRadioButton("Wire", this);
    rad_but_type_polygon = new QRadioButton("Polygon", this);
    rad_but_type_extruded_polygon = new QRadioButton("Extruded polygon", this);
    rad_but_type_rotational_solid = new QRadioButton("Rotational Solid", this);
    rad_but_type_polyhedron = new QRadioButton("Polyhedron", this);
    connect(rad_but_type_box, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_sphere, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_spherical_shell, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_cylinder, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_cylindrical_shell, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_curve, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_wire, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_polygon, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_extruded_polygon, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_rotational_solid, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    connect(rad_but_type_polyhedron, SIGNAL(clicked()), this, SLOT(OnSetShapeTypeLayout()));
    rad_but_type_box->setChecked(true);

    grid_layout_select_shape->addWidget(rad_but_type_box, 0, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_sphere, 1, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_spherical_shell, 2, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_cylinder, 3, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_cylindrical_shell, 4, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_curve, 5, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_wire, 6, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_polygon, 7, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_extruded_polygon, 8, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_rotational_solid, 9, 0, Qt::AlignLeft);
    grid_layout_select_shape->addWidget(rad_but_type_polyhedron, 10, 0, Qt::AlignLeft);

    shape_select_groupbox->setLayout(grid_layout_select_shape);
}


void PageGeometry::ShapeListLayout(void)
{
    shape_list_groupbox = new QGroupBox(tr("Shapes list"));
    QGridLayout *grid_layout_shape_list = new QGridLayout;

    shapes_list_widget = new QListWidget(this);
    connect(shapes_list_widget, SIGNAL(itemClicked(QListWidgetItem*)), this, SLOT(OnGetSelectedShape(QListWidgetItem*)));

    QPushButton *button_add_edit_shape = new QPushButton("New/Edit", this);
    connect(button_add_edit_shape, SIGNAL(released()), this, SLOT(OnAddOrChangeShape()));
    QPushButton *button_remove_shape = new QPushButton("Remove", this);
    connect(button_remove_shape, SIGNAL(released()), this, SLOT(OnRemoveShape()));

    grid_layout_shape_list->addWidget(button_add_edit_shape, 8, 0, Qt::AlignLeft);
    grid_layout_shape_list->addWidget(button_remove_shape, 8, 1, Qt::AlignLeft);
    grid_layout_shape_list->addWidget(shapes_list_widget, 0, 0, 7, 2, Qt::AlignLeft);

    shape_list_groupbox->setLayout(grid_layout_shape_list);
}

void PageGeometry::ShapeTransformsLayout(void)  //settings of transformations (move, rotate, scale) of shapes
{
    //main groupbox and layout
    transforms_groupbox = new QGroupBox(tr("Transforms"));
    QVBoxLayout *vert_layout_transforms = new QVBoxLayout;

    //selecting order of transforms
    QGroupBox *groupbox_transf_order = new QGroupBox(tr("Order of transforms"));
    QGridLayout *grid_layout_transf_order = new QGridLayout;
    transforms_list_widget = new QListWidget(this);
    button_transform_scale = new QPushButton("Scale", this);
    connect(button_transform_scale, SIGNAL(released()), this, SLOT(OnChangeTransformOrder()));
    button_transform_rotate = new QPushButton("Rotate", this);
    connect(button_transform_rotate, SIGNAL(released()), this, SLOT(OnChangeTransformOrder()));
    button_transform_move = new QPushButton("Move", this);
    connect(button_transform_move, SIGNAL(released()), this, SLOT(OnChangeTransformOrder()));
    button_transform_remove = new QPushButton("Remove", this);
    connect(button_transform_remove, SIGNAL(released()), this, SLOT(OnChangeTransformOrder()));
    grid_layout_transf_order->addWidget(transforms_list_widget, 0, 0, 3, 1, Qt::AlignLeft);
    grid_layout_transf_order->addWidget(button_transform_scale, 0, 1, Qt::AlignLeft);
    grid_layout_transf_order->addWidget(button_transform_rotate, 1, 1, Qt::AlignLeft);
    grid_layout_transf_order->addWidget(button_transform_move, 2, 1, Qt::AlignLeft);
    grid_layout_transf_order->addWidget(button_transform_remove, 3, 1, Qt::AlignLeft);
    groupbox_transf_order->setLayout(grid_layout_transf_order);

    //controls for scale transform
    QGroupBox *groupbox_transf_scale = new QGroupBox(tr("Scale"));
    QGridLayout *grid_layout_scale = new QGridLayout;
    QLabel *transf_statictext_scale_x = new QLabel("x", this);
    QLabel *transf_statictext_scale_y = new QLabel("y", this);
    QLabel *transf_statictext_scale_z = new QLabel("z", this);
    transf_scale_x = new QLineEdit(this);
    transf_scale_y = new QLineEdit(this);
    transf_scale_z = new QLineEdit(this);
    grid_layout_scale->addWidget(transf_statictext_scale_x, 0, 1, Qt::AlignLeft);
    grid_layout_scale->addWidget(transf_statictext_scale_y, 0, 2, Qt::AlignLeft);
    grid_layout_scale->addWidget(transf_statictext_scale_z, 0, 3, Qt::AlignLeft);
    grid_layout_scale->addWidget(transf_scale_x, 1, 1, Qt::AlignLeft);
    grid_layout_scale->addWidget(transf_scale_y, 1, 2, Qt::AlignLeft);
    grid_layout_scale->addWidget(transf_scale_z, 1, 3, Qt::AlignLeft);
    groupbox_transf_scale->setLayout(grid_layout_scale);

    //controls for rotate transform
    QGroupBox *groupbox_transf_rotate = new QGroupBox(tr("Rotate"));
    QGridLayout *grid_layout_rotate = new QGridLayout;
    QLabel *transf_statictext_rot_ax = new QLabel("axis x", this);
    QLabel *transf_statictext_rot_ay = new QLabel("axis y", this);
    QLabel *transf_statictext_rot_az = new QLabel("axis z", this);
    QLabel *transf_statictext_rot_angle = new QLabel("angle", this);
    transf_rotate_ax = new QLineEdit(this);
    transf_rotate_ay = new QLineEdit(this);
    transf_rotate_az = new QLineEdit(this);
    transf_rotate_angle = new QLineEdit(this);
    grid_layout_rotate->addWidget(transf_statictext_rot_ax, 0, 1, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_statictext_rot_ay, 0, 2, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_statictext_rot_az, 0, 3, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_rotate_ax, 1, 1, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_rotate_ay, 1, 2, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_rotate_az, 1, 3, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_statictext_rot_angle, 2, 1, 1, 3, Qt::AlignLeft);
    grid_layout_rotate->addWidget(transf_rotate_angle, 3, 1, 1, 3, Qt::AlignLeft);
    groupbox_transf_rotate->setLayout(grid_layout_rotate);

    //controls for move transform
    QGroupBox *groupbox_transf_move = new QGroupBox(tr("Move"));
    QGridLayout *grid_layout_move = new QGridLayout;
    QLabel *transf_statictext_move_x = new QLabel("x", this);
    QLabel *transf_statictext_move_y = new QLabel("y", this);
    QLabel *transf_statictext_move_z = new QLabel("z", this);
    transf_move_x = new QLineEdit(this);
    transf_move_y = new QLineEdit(this);
    transf_move_z = new QLineEdit(this);
    grid_layout_move->addWidget(transf_statictext_move_x, 0, 1, Qt::AlignLeft);
    grid_layout_move->addWidget(transf_statictext_move_y, 0, 2, Qt::AlignLeft);
    grid_layout_move->addWidget(transf_statictext_move_z, 0, 3, Qt::AlignLeft);
    grid_layout_move->addWidget(transf_move_x, 1, 1, Qt::AlignLeft);
    grid_layout_move->addWidget(transf_move_y, 1, 2, Qt::AlignLeft);
    grid_layout_move->addWidget(transf_move_z, 1, 3, Qt::AlignLeft);
    groupbox_transf_move->setLayout(grid_layout_move);

    //adding groups of controls to main layout
    vert_layout_transforms->addWidget(groupbox_transf_order);
    vert_layout_transforms->addWidget(groupbox_transf_scale);
    vert_layout_transforms->addWidget(groupbox_transf_rotate);
    vert_layout_transforms->addWidget(groupbox_transf_move);
    transforms_groupbox->setLayout(vert_layout_transforms);
}

void PageGeometry::ShapeBoxSettings(void)
{
    groupbox_box_settings = new QGroupBox(tr("Box settings"));
    QGridLayout *grid_layout_shape_box = new QGridLayout;

    QLabel *sh_box_statictext_name = new QLabel("name", this);
    sh_box_name = new QLineEdit(this);
    QLabel *sh_box_statictext_priority = new QLabel("priority", this);
    sh_box_priority = new QLineEdit(this);
    QLabel *sh_box_statictext_xstart = new QLabel("x start", this);
    sh_box_x_coord_1 = new QComboBox(this);
    sh_box_x_coord_1->setEditable(true);
connect(var_edit, SIGNAL(VarEdit()), this, SLOT(UpdateVariableLists()));
    QLabel *sh_box_statictext_xstop = new QLabel("x stop", this);
    sh_box_x_coord_2 = new QLineEdit(this);
    QLabel *sh_box_statictext_ystart = new QLabel("y start", this);
    sh_box_y_coord_1 = new QLineEdit(this);
    QLabel *sh_box_statictext_ystop = new QLabel("y stop", this);
    sh_box_y_coord_2 = new QLineEdit(this);
    QLabel *sh_box_statictext_zstart = new QLabel("z start", this);
    sh_box_z_coord_1 = new QLineEdit(this);
    QLabel *sh_box_statictext_zstop = new QLabel("z stop", this);
    sh_box_z_coord_2 = new QLineEdit(this);
    QLabel *sh_box_statictext_material = new QLabel("material", this);
    sh_box_material = new QComboBox(this);
    QLabel *sh_box_statictext_placeholder = new QLabel("", this);

    connect(sh_box_name, SIGNAL(editingFinished()), this, SLOT(OnSetShapeTypeLayout()));

    grid_layout_shape_box->addWidget(sh_box_statictext_name, 0, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_priority, 1, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_xstart, 2, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_xstop, 3, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_ystart, 4, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_ystop, 5, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_zstart, 6, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_zstop, 7, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_material, 8, 0, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_statictext_placeholder, 9, 0, Qt::AlignLeft);

    grid_layout_shape_box->addWidget(sh_box_name, 0, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_priority, 1, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_x_coord_1, 2, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_x_coord_2, 3, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_y_coord_1, 4, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_y_coord_2, 5, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_z_coord_1, 6, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_z_coord_2, 7, 1, Qt::AlignLeft);
    grid_layout_shape_box->addWidget(sh_box_material, 8, 1, Qt::AlignLeft);

    groupbox_box_settings->setLayout(grid_layout_shape_box);
}

void PageGeometry::ShapeCylinderSettings(void)
{
    groupbox_cylinder_settings = new QGroupBox(tr("Cylinder settings"));
    QGridLayout *grid_layout_shape_cylinder = new QGridLayout;

    QLabel *sh_cylinder_statictext_name = new QLabel("name", this);
    sh_cylinder_name = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_priority = new QLabel("priority", this);
    sh_cylinder_priority = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_xstart = new QLabel("x start", this);
    sh_cylinder_x_coord_1 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_xstop = new QLabel("x stop", this);
    sh_cylinder_x_coord_2 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_ystart = new QLabel("y start", this);
    sh_cylinder_y_coord_1 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_ystop = new QLabel("y stop", this);
    sh_cylinder_y_coord_2 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_zstart = new QLabel("z start", this);
    sh_cylinder_z_coord_1 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_zstop = new QLabel("z stop", this);
    sh_cylinder_z_coord_2 = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_radius = new QLabel("radius", this);
    sh_cylinder_radius = new QLineEdit(this);
    QLabel *sh_cylinder_statictext_material = new QLabel("material", this);
    sh_cylinder_material = new QComboBox(this);

    connect(sh_cylinder_name, SIGNAL(editingFinished()), this, SLOT(OnSetShapeTypeLayout()));

    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_name, 0, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_priority, 1, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_xstart, 2, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_xstop, 3, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_ystart, 4, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_ystop, 5, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_zstart, 6, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_zstop, 7, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_radius, 8, 0, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_statictext_material, 9, 0, Qt::AlignLeft);

    grid_layout_shape_cylinder->addWidget(sh_cylinder_name, 0, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_priority, 1, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_x_coord_1, 2, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_x_coord_2, 3, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_y_coord_1, 4, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_y_coord_2, 5, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_z_coord_1, 6, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_z_coord_2, 7, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_radius, 8, 1, Qt::AlignLeft);
    grid_layout_shape_cylinder->addWidget(sh_cylinder_material, 9, 1, Qt::AlignLeft);

    groupbox_cylinder_settings->setLayout(grid_layout_shape_cylinder);
}

void PageGeometry::OnAddOrChangeShape(void)
{
    if(rad_but_type_box->isChecked())
    {
        shape_box_parameters *shape_tmp_ptr = new shape_box_parameters;
        shape_tmp_ptr->name = sh_box_name->text();
        shape_tmp_ptr->type = "box";
        shape_tmp_ptr->priority = sh_box_priority->text();
        shape_tmp_ptr->x_coord_1 = sh_box_x_coord_1->currentText();
        shape_tmp_ptr->x_coord_2 = sh_box_x_coord_2->text();
        shape_tmp_ptr->y_coord_1 = sh_box_y_coord_1->text();
        shape_tmp_ptr->y_coord_2 = sh_box_y_coord_2->text();
        shape_tmp_ptr->z_coord_1 = sh_box_z_coord_1->text();
        shape_tmp_ptr->z_coord_2 = sh_box_z_coord_2->text();
        shape_tmp_ptr->material = sh_box_material->currentText();
        shape_tmp_ptr->transf_scale_x = transf_scale_x->text();
        shape_tmp_ptr->transf_scale_y = transf_scale_y->text();
        shape_tmp_ptr->transf_scale_z = transf_scale_z->text();
        shape_tmp_ptr->transf_rotate_ax = transf_rotate_ax->text();
        shape_tmp_ptr->transf_rotate_ay = transf_rotate_ay->text();
        shape_tmp_ptr->transf_rotate_az = transf_rotate_az->text();
        shape_tmp_ptr->transf_rotate_angle = transf_rotate_angle->text();
        shape_tmp_ptr->transf_move_x = transf_move_x->text();
        shape_tmp_ptr->transf_move_y = transf_move_y->text();
        shape_tmp_ptr->transf_move_z = transf_move_z->text();
        for(int i_tr = 0; i_tr < 3; ++i_tr)
        {
            if(i_tr < transforms_list_widget->count())
                shape_tmp_ptr->transf_order[i_tr] = transforms_list_widget->item(i_tr)->text();
            else
                shape_tmp_ptr->transf_order[i_tr] = "";
        }

        if(!shape_tmp_ptr->name.isEmpty())
        {
            if(shapes_param_list_ptr->empty())
            {
                shapes_param_list_ptr->push_back(shape_tmp_ptr);
                shapes_list_widget->addItem(shapes_param_list_ptr->at(shapes_param_list_ptr->size()-1)->name);
                shapes_list_widget->setCurrentRow(shapes_list_widget->count()-1);
            }
            else if(shapes_param_list_ptr->at(shapes_list_widget->currentRow())->name != shape_tmp_ptr->name)
            {
                shapes_param_list_ptr->push_back(shape_tmp_ptr);
                shapes_list_widget->addItem(shapes_param_list_ptr->at(shapes_param_list_ptr->size()-1)->name);
                shapes_list_widget->setCurrentRow(shapes_list_widget->count()-1);
            }
            else if(shapes_param_list_ptr->at(shapes_list_widget->currentRow())->name == shape_tmp_ptr->name)
            {
                shapes_param_list_ptr->replace(shapes_list_widget->currentRow(), shape_tmp_ptr);
            }
        }
    }
    else if(rad_but_type_cylinder->isChecked())
    {
        shape_cylinder_parameters *shape_tmp_ptr = new shape_cylinder_parameters;
        shape_tmp_ptr->name = sh_cylinder_name->text();
        shape_tmp_ptr->type = "cylinder";
        shape_tmp_ptr->priority = sh_cylinder_priority->text();
        shape_tmp_ptr->x_coord_1 = sh_cylinder_x_coord_1->text();
        shape_tmp_ptr->x_coord_2 = sh_cylinder_x_coord_2->text();
        shape_tmp_ptr->y_coord_1 = sh_cylinder_y_coord_1->text();
        shape_tmp_ptr->y_coord_2 = sh_cylinder_y_coord_2->text();
        shape_tmp_ptr->z_coord_1 = sh_cylinder_z_coord_1->text();
        shape_tmp_ptr->z_coord_2 = sh_cylinder_z_coord_2->text();
        shape_tmp_ptr->radius = sh_cylinder_radius->text();
        shape_tmp_ptr->material = sh_cylinder_material->currentText();

        if(!shape_tmp_ptr->name.isEmpty())
        {
            if(shapes_param_list_ptr->empty())
            {
                shapes_param_list_ptr->push_back(shape_tmp_ptr);
                shapes_list_widget->addItem(shapes_param_list_ptr->at(shapes_param_list_ptr->size()-1)->name);
                shapes_list_widget->setCurrentRow(shapes_list_widget->count()-1);
            }
            else if(shapes_param_list_ptr->at(shapes_list_widget->currentRow())->name != shape_tmp_ptr->name)
            {
                shapes_param_list_ptr->push_back(shape_tmp_ptr);
                shapes_list_widget->addItem(shapes_param_list_ptr->at(shapes_param_list_ptr->size()-1)->name);
                shapes_list_widget->setCurrentRow(shapes_list_widget->count()-1);
            }
            else if(shapes_param_list_ptr->at(shapes_list_widget->currentRow())->name == shape_tmp_ptr->name)
            {
                shapes_param_list_ptr->replace(shapes_list_widget->currentRow(), shape_tmp_ptr);
            }
        }
    }
}



void PageGeometry::OnRemoveShape(void)
{
    if(!shapes_param_list_ptr->empty())
    {        
        shape_parameters *shape_to_del = shapes_param_list_ptr->at(shapes_list_widget->currentRow());

        shapes_param_list_ptr->remove(shapes_list_widget->currentRow());
        shapes_list_widget->takeItem(shapes_list_widget->currentRow());

        delete shape_to_del;    //TODO FIXME i dont know if it's the right way to delete shape item created by "new" in OnAddOrChangeShape
    }
}



void PageGeometry::OnGetSelectedShape(QListWidgetItem* item)
{
    shape_parameters *shape_tmp_ptr;
    shape_tmp_ptr = shapes_param_list_ptr->at(shapes_list_widget->currentRow());

    if(!QString::compare(shape_tmp_ptr->type, "box"))
    {
        shape_box_parameters *shape_box_tmp = (shape_box_parameters *)(shape_tmp_ptr);
        rad_but_type_box->setChecked(true);
        sh_box_name->setText(shape_box_tmp->name);
        sh_box_priority->setText(shape_box_tmp->priority);
        sh_box_x_coord_1->setEditText(shape_box_tmp->x_coord_1);
        sh_box_x_coord_2->setText(shape_box_tmp->x_coord_2);
        sh_box_y_coord_1->setText(shape_box_tmp->y_coord_1);
        sh_box_y_coord_2->setText(shape_box_tmp->y_coord_2);
        sh_box_z_coord_1->setText(shape_box_tmp->z_coord_1);
        sh_box_z_coord_2->setText(shape_box_tmp->z_coord_2);
        sh_box_material->setCurrentIndex(sh_box_material->findText(shape_box_tmp->material));
        transf_scale_x->setText(shape_tmp_ptr->transf_scale_x);
        transf_scale_y->setText(shape_tmp_ptr->transf_scale_y);
        transf_scale_z->setText(shape_tmp_ptr->transf_scale_z);
        transf_rotate_ax->setText(shape_tmp_ptr->transf_rotate_ax);
        transf_rotate_ay->setText(shape_tmp_ptr->transf_rotate_ay);
        transf_rotate_az->setText(shape_tmp_ptr->transf_rotate_az);
        transf_rotate_angle->setText(shape_tmp_ptr->transf_rotate_angle);
        transf_move_x->setText(shape_tmp_ptr->transf_move_x);
        transf_move_y->setText(shape_tmp_ptr->transf_move_y);
        transf_move_z->setText(shape_tmp_ptr->transf_move_z);
        transforms_list_widget->clear();
        button_transform_move->hide();
        button_transform_scale->hide();
        button_transform_rotate->hide();
        for(int i_tr = 0; i_tr < 3; ++i_tr)
        {
            if(shape_tmp_ptr->transf_order[i_tr] != "")
                transforms_list_widget->addItem(shape_tmp_ptr->transf_order[i_tr]);
            if(shape_tmp_ptr->transf_order[i_tr] == "Move")
                button_transform_move->show();
            if(shape_tmp_ptr->transf_order[i_tr] == "Scale")
                button_transform_scale->show();
            if(shape_tmp_ptr->transf_order[i_tr] == "Rotate")
                button_transform_rotate->show();
        }
    }
    else if(!QString::compare(shape_tmp_ptr->type, "cylinder"))
    {
        shape_cylinder_parameters *shape_cylinder_tmp = (shape_cylinder_parameters *)(shape_tmp_ptr);
        rad_but_type_cylinder->setChecked(true);
        sh_cylinder_name->setText(shape_cylinder_tmp->name);
        sh_cylinder_priority->setText(shape_cylinder_tmp->priority);
        sh_cylinder_x_coord_1->setText(shape_cylinder_tmp->x_coord_1);
        sh_cylinder_x_coord_2->setText(shape_cylinder_tmp->x_coord_2);
        sh_cylinder_y_coord_1->setText(shape_cylinder_tmp->y_coord_1);
        sh_cylinder_y_coord_2->setText(shape_cylinder_tmp->y_coord_2);
        sh_cylinder_z_coord_1->setText(shape_cylinder_tmp->z_coord_1);
        sh_cylinder_z_coord_2->setText(shape_cylinder_tmp->z_coord_2);
        sh_cylinder_radius->setText(shape_cylinder_tmp->radius);
        sh_cylinder_material->setCurrentIndex(sh_cylinder_material->findText(shape_cylinder_tmp->material));
    }

    OnSetShapeTypeLayout();
}


void PageGeometry::OnSetShapeTypeLayout(void)   //called to change layout according to selection of shape type and to select proper shape on the list (according to name, to prevent adding more items with the same name)
{
    if(rad_but_type_box->isChecked())
    {
        stackedLayout->setCurrentIndex(0);
        for(int i = 0 ; i < shapes_list_widget->count(); ++i)
            if(shapes_list_widget->item(i)->text() == sh_box_name->text())
                shapes_list_widget->setCurrentRow(i);
    }
    else if(rad_but_type_cylinder->isChecked())
    {
        stackedLayout->setCurrentIndex(1);
        for(int i = 0 ; i < shapes_list_widget->count(); ++i)
            if(shapes_list_widget->item(i)->text() == sh_cylinder_name->text())
                shapes_list_widget->setCurrentRow(i);
    }
}


void PageGeometry::initializePage()
{
    UpdateVariableLists();
}


void PageGeometry::UpdateVariableLists(void)
{
    sh_box_x_coord_1->clear();
    for(int i_expr = 0; i_expr < var_edit->GetVarTable()->rowCount(); ++i_expr)
        if((var_edit->GetVarTable()->item(i_expr, 0) != NULL) && (var_edit->GetVarTable()->item(i_expr, 1) != NULL))
            sh_box_x_coord_1->addItem(var_edit->GetVarTable()->item(i_expr,0)->text());
}


QString PageGeometry::EvaluateVar(QString var_to_eval)
{
    return var_edit->GetExprEngine()->evaluate(var_to_eval).toString();
}


void PageGeometry::OnChangeTransformOrder(void)
{
    QPushButton* buttonSender = qobject_cast<QPushButton*>(sender()); // retrieve the button you have clicked
    QString buttonText = buttonSender->text(); // retrive the text from the button clicked

    if(buttonText == "Scale")
    {
        transforms_list_widget->addItem("Scale");
        buttonSender->hide();
    }
    if(buttonText == "Rotate")
    {
        transforms_list_widget->addItem("Rotate");
        buttonSender->hide();
    }
    if(buttonText == "Move")
    {
        transforms_list_widget->addItem("Move");
        buttonSender->hide();
    }
    if(buttonText == "Remove" && transforms_list_widget->count())
    {
        button_transform_scale->show();
        button_transform_rotate->show();
        button_transform_move->show();
        transforms_list_widget->clear();

    }
}
