#include "PagePorts.h"

PagePorts::PagePorts(QWizard *parent): QWizardPage(parent)
{
    QLabel *statictext_TODO = new QLabel("Configuration of ports and excitation TO BE DONE", this);
    statictext_TODO->setGeometry(QRect(QPoint(22, 20), QSize(500, 30)));

}


bool PagePorts::validatePage()
{
    SaveToSimScriptBuffer();
    return true;
}


void PagePorts::SaveToSimScriptBuffer(void)
{
    text_save_to_simscript.clear();
    text_save_to_simscript.append("##<OUTPUT_AUTOGENERATED_PagePorts>##\n");


    text_save_to_simscript.append("##<END_OUTPUT_AUTOGENERATED_PagePorts>##\n");
    qDebug("%s", qUtf8Printable(text_save_to_simscript));
}


void PagePorts::ReadFromSimScriptBuffer(void)
{

}
