#include "page_ports.h"

PagePorts::PagePorts(QWizard *parent): QWizardPage(parent)
{

}


bool PagePorts::validatePage()
{
    SaveToSimScriptBuffer();
    return true;
}


void PagePorts::SaveToSimScriptBuffer(void)
{
    text_save_to_simscript.clear();
    text_save_to_simscript.append("##<OUTPUT_AUTOGENERATED_PagePorts>##\n");


    text_save_to_simscript.append("##<END_OUTPUT_AUTOGENERATED_PagePorts>##\n");
    qDebug("%s", qUtf8Printable(text_save_to_simscript));
}


void PagePorts::ReadFromSimScriptBuffer(void)
{

}
