#include "PageGeneralGeometrySettings.h"
#include <QDebug>


PageGeneralGeometrySettings::PageGeneralGeometrySettings(QWizard *parent): QWizardPage(parent)
{
    ConfigSimBox();
}


bool PageGeneralGeometrySettings::validatePage()
{
    SaveToSimScriptBuffer();
    return true;
}


void PageGeneralGeometrySettings::SaveToSimScriptBuffer(void)
{
    text_save_to_simscript.clear();
    text_save_to_simscript.append("##<OUTPUT_AUTOGENERATED_PageGeneralGeometrySettings>##\n");
    text_save_to_simscript.append(QString("unit = %1;\n").arg(GetUnitMultiplier()));
    text_save_to_simscript.append(QString("mesh_start_x = %1;\n").arg(text_bb_nx->text()));
    text_save_to_simscript.append(QString("mesh_stop_x = %1;\n").arg(text_bb_px->text()));
    text_save_to_simscript.append(QString("mesh_start_y = %1;\n").arg(text_bb_ny->text()));
    text_save_to_simscript.append(QString("mesh_stop_y = %1;\n").arg(text_bb_py->text()));
    text_save_to_simscript.append(QString("mesh_start_z = %1;\n").arg(text_bb_nz->text()));
    text_save_to_simscript.append(QString("mesh_stop_z = %1;\n").arg(text_bb_pz->text()));
    text_save_to_simscript.append(QString("BC = {'%1' '%2' '%3' '%4' '%5' '%6'};\n").arg(combo_bb_nx->currentText()).arg(combo_bb_px->currentText()).arg(combo_bb_ny->currentText()).arg(combo_bb_py->currentText()).arg(combo_bb_nz->currentText()).arg(combo_bb_pz->currentText()));
    text_save_to_simscript.append(QString("FDTD = SetBoundaryCond(FDTD, BC);\n"));
//    FDTD = SetGaussExcite(FDTD, (fmax+fmin)/2, (fmax-fmin)/2);  #finite energy excitation
    text_save_to_simscript.append("##<END_OUTPUT_AUTOGENERATED_PageGeneralGeometrySettings>##\n");
    qDebug("%s", qUtf8Printable(text_save_to_simscript));
}


void PageGeneralGeometrySettings::ReadFromSimScriptBuffer(void)
{

}


void PageGeneralGeometrySettings::ConfigSimBox(void)
{
    group_box_sim_par = new QGroupBox(tr("simulation box"), this);
    grid_sim_par = new QGridLayout(this);
    grid_sim_par->setSizeConstraint(QLayout::SetFixedSize);
    grid_sim_par->setColumnMinimumWidth(3, 50);

    QLabel *statictext_unit = new QLabel("unit", this);
    combo_unit = new QComboBox(this);
    combo_unit->addItem("m");
    combo_unit->addItem("mm");
    combo_unit->addItem("um");

    QLabel *statictext_nx = new QLabel("-x", this);
    text_bb_nx = new QLineEdit(this);
    text_bb_nx->setFixedWidth(50);
    combo_bb_nx = new QComboBox(this);
    combo_bb_nx->addItem("PML8");
    combo_bb_nx->addItem("PEC");
    combo_bb_nx->addItem("MUR");

    QLabel *statictext_px = new QLabel("+x", this);
    text_bb_px = new QLineEdit(this);
    text_bb_px->setFixedWidth(50);
    combo_bb_px = new QComboBox(this);
    combo_bb_px->addItem("PML8");
    combo_bb_px->addItem("PEC");
    combo_bb_px->addItem("MUR");

    QLabel *statictext_ny = new QLabel("-y", this);
    text_bb_ny = new QLineEdit(this);
    text_bb_ny->setFixedWidth(50);
    combo_bb_ny = new QComboBox(this);
    combo_bb_ny->addItem("PML8");
    combo_bb_ny->addItem("PEC");
    combo_bb_ny->addItem("MUR");

    QLabel *statictext_py = new QLabel("+y", this);
    text_bb_py = new QLineEdit(this);
    text_bb_py->setFixedWidth(50);
    combo_bb_py = new QComboBox(this);
    combo_bb_py->addItem("PML8");
    combo_bb_py->addItem("PEC");
    combo_bb_py->addItem("MUR");

    QLabel *statictext_nz = new QLabel("-z", this);
    text_bb_nz = new QLineEdit(this);
    text_bb_nz->setFixedWidth(50);
    combo_bb_nz = new QComboBox(this);
    combo_bb_nz->addItem("PML8");
    combo_bb_nz->addItem("PEC");
    combo_bb_nz->addItem("MUR");

    QLabel *statictext_pz = new QLabel("+z", this);
    text_bb_pz = new QLineEdit(this);
    text_bb_pz->setFixedWidth(50);
    combo_bb_pz = new QComboBox(this);
    combo_bb_pz->addItem("PML8");
    combo_bb_pz->addItem("PEC");
    combo_bb_pz->addItem("MUR");

    grid_sim_par->addWidget(statictext_unit, 0, 0, Qt::AlignRight);
    grid_sim_par->addWidget(combo_unit, 0, 1, Qt::AlignLeft);

    grid_sim_par->addWidget(statictext_nx, 2, 0, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_nx, 2, 1, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_nx, 2, 2, Qt::AlignLeft);
    grid_sim_par->addWidget(statictext_px, 2, 4, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_px, 2, 5, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_px, 2, 6, Qt::AlignLeft);

    grid_sim_par->addWidget(statictext_ny, 3, 0, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_ny, 3, 1, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_ny, 3, 2, Qt::AlignLeft);
    grid_sim_par->addWidget(statictext_py, 3, 4, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_py, 3, 5, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_py, 3, 6, Qt::AlignLeft);

    grid_sim_par->addWidget(statictext_nz, 4, 0, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_nz, 4, 1, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_nz, 4, 2, Qt::AlignLeft);
    grid_sim_par->addWidget(statictext_pz, 4, 4, Qt::AlignLeft);
    grid_sim_par->addWidget(text_bb_pz, 4, 5, Qt::AlignLeft);
    grid_sim_par->addWidget(combo_bb_pz, 4, 6, Qt::AlignLeft);

    group_box_sim_par->setLayout(grid_sim_par);
}
